// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zeottnzytpcbinxtlywt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inplb3R0bnp5dHBjYmlueHRseXd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5ODQ0MzQsImV4cCI6MjA2NDU2MDQzNH0.wlIEhBYtOObbzhAFxbZPBlGI1HMp5YW0Do2BKVCLtw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);