// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fanckbxnbxidcdleenpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhbmNrYnhuYnhpZGNkbGVlbnB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5Mzc5MjMsImV4cCI6MjA2NDUxMzkyM30.U468Q8_2VzmN6J053s7MCEff_F8FHUmj4hTIKxUP-QA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);